version: '3'

services:
  app:
    build:
      context: .docker/prisma-api
    entrypoint: .docker/prisma-api/entrypoint.sh
    container_name: prismaapi-app
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: prismaapi-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=primaapi

volumes:
  dbdata:
